// packages/typescript/ai-solid-ui/src/text-part.tsx
import { createSignal, onMount, Show } from 'solid-js'
import type { Component } from 'solid-js'

export interface TextPartProps {
  /** The text content to render */
  content: string
  /** The role of the message (user, assistant, or system) - optional for standalone use */
  role?: 'user' | 'assistant' | 'system'
  /** Base class applied to all text parts */
  class?: string
  /** Additional class for user messages */
  userClass?: string
  /** Additional class for assistant messages (also used for system messages) */
  assistantClass?: string
}

// Lazy load SolidMarkdown and plugins to avoid SSR issues
let SolidMarkdown: Component<any> | null = null
let remarkGfm: any = null
let rehypeRaw: any = null
let rehypeSanitize: any = null
let rehypeHighlight: any = null

/**
 * TextPart component - renders markdown text with syntax highlighting
 *
 * Features:
 * - Full markdown support with GFM (tables, strikethrough, etc.)
 * - Syntax highlighting for code blocks
 * - Sanitized HTML rendering
 * - Role-based styling (user vs assistant)
 *
 * @example Standalone usage
 * ```tsx
 * <TextPart
 *   content="Hello **world**!"
 *   role="user"
 *   class="p-4 rounded"
 *   userClass="bg-blue-500"
 *   assistantClass="bg-gray-500"
 * />
 * ```
 *
 * @example Usage in partRenderers
 * ```tsx
 * <ChatMessage
 *   message={message}
 *   partRenderers={{
 *     text: ({ content }) => (
 *       <TextPart
 *         content={content}
 *         role={message.role}
 *         class="px-5 py-3 rounded-2xl"
 *         userClass="bg-orange-500 text-white"
 *         assistantClass="bg-gray-800 text-white"
 *       />
 *     )
 *   }}
 * />
 * ```
 */
export function TextPart(props: TextPartProps) {
  const [isClient, setIsClient] = createSignal(false)
  const [isLoaded, setIsLoaded] = createSignal(false)

  // Combine classes based on role
  const roleClass = () =>
    props.role === 'user'
      ? props.userClass ?? ''
      : props.role === 'assistant'
        ? props.assistantClass ?? ''
        : ''
  const combinedClass = () =>
    [props.class ?? '', roleClass()].filter(Boolean).join(' ')

  onMount(async () => {
    setIsClient(true)
    // Dynamically import solid-markdown and plugins only on the client
    const [markdownModule, gfmModule, rawModule, sanitizeModule, highlightModule] = await Promise.all([
      import('solid-markdown'),
      import('remark-gfm'),
      import('rehype-raw'),
      import('rehype-sanitize'),
      import('rehype-highlight'),
    ])
    SolidMarkdown = markdownModule.SolidMarkdown
    remarkGfm = gfmModule.default
    rehypeRaw = rawModule.default
    rehypeSanitize = sanitizeModule.default
    rehypeHighlight = highlightModule.default
    setIsLoaded(true)
  })

  return (
    <div class={combinedClass() || undefined}>
      <Show when={isClient() && isLoaded() && SolidMarkdown} fallback={<span>{props.content}</span>}>
        {(_) => {
          const Markdown = SolidMarkdown!
          return (
            <Markdown
              remarkPlugins={[remarkGfm]}
              rehypePlugins={[rehypeRaw, rehypeSanitize, rehypeHighlight]}
            >
              {props.content}
            </Markdown>
          )
        }}
      </Show>
    </div>
  )
}

// packages/ai-react-ui/src/text-part.tsx
import ReactMarkdown from 'react-markdown'
import { resolveMarkdownPlugins } from './markdown-plugins'
import type { Components } from 'react-markdown'
import type { PluggableList } from './markdown-plugins'

export interface TextPartProps {
  /** The text content to render */
  content: string
  /** The role of the message (user, assistant, or system) - optional for standalone use */
  role?: 'user' | 'assistant' | 'system'
  /** Base className applied to all text parts */
  className?: string
  /** Additional className for user messages */
  userClassName?: string
  /** Additional className for assistant messages (also used for system messages) */
  assistantClassName?: string
  /**
     * Additional remark plugins, appended after the defaults
     * (or replacing them when `disableDefaultPlugins` is true).
     */
  remarkPlugins?: PluggableList
  /**
     * Additional rehype plugins. Inserted between the built-in
     * `rehypeRaw`/`rehypeHighlight` and the trailing `rehypeSanitize`
     * so sanitization always runs last. When `disableDefaultPlugins`
     * is true, replaces the entire chain.
     */
  rehypePlugins?: PluggableList
  /** react-markdown `components` overrides (e.g. custom `a`, `code`). */
  components?: Components
  /**
     * Drop the built-in plugin defaults entirely. The consumer becomes
     * responsible for syntax highlighting, GFM, raw HTML handling, and
     * sanitization. Use with care — disabling defaults removes the
     * built-in XSS sanitizer.
     */
  disableDefaultPlugins?: boolean
}

/**
 * TextPart component - renders markdown text with syntax highlighting.
 *
 * @example Standalone usage
 * ```tsx
 * <TextPart
 *   content="Hello **world**!"
 *   role="user"
 *   className="p-4 rounded"
 *   userClassName="bg-blue-500"
 *   assistantClassName="bg-gray-500"
 * />
 * ```
 *
 * @example Add a markdown plugin (e.g. CJK bold/emphasis support)
 * ```tsx
 * import remarkCjkFriendly from 'remark-cjk-friendly'
 *
 * <TextPart content={content} remarkPlugins={[remarkCjkFriendly]} />
 * ```
 */
export function TextPart({
  content,
  role,
  className = '',
  userClassName = '',
  assistantClassName = '',
  remarkPlugins,
  rehypePlugins,
  components,
  disableDefaultPlugins,
}: TextPartProps) {
  const roleClassName =
    role === 'user'
      ? userClassName
      : role === 'assistant'
        ? assistantClassName
        : ''
  const combinedClassName = [className, roleClassName].filter(Boolean).join(' ')

  const resolved = resolveMarkdownPlugins({
    remarkPlugins,
    rehypePlugins,
    disableDefaultPlugins,
  })

  return (
    <div className={combinedClassName || undefined}>
      <ReactMarkdown
        remarkPlugins={resolved.remarkPlugins}
        rehypePlugins={resolved.rehypePlugins}
        components={components}
      >
        {content}
      </ReactMarkdown>
    </div>
  )
}
