// packages/ai-react/src/use-web-mcp-tools.ts
import { useEffect, useRef, useState } from 'react'
import { registerWebMCPTools, subscribeWebMCPTools } from '@tanstack/ai-client'
import type {
  AnyClientTool,
  InferredClientContext,
  RegisterWebMCPToolsOptions,
  SubscribeWebMCPToolsOptions,
} from '@tanstack/ai-client'

/** Options for the React {@link useRegisterWebMCPTools} lifecycle hook. */
export type UseRegisterWebMCPToolsOptions<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
> = Omit<RegisterWebMCPToolsOptions<TTools, TContext>, 'signal'> & {
  /** Receives an asynchronous registration failure. */
  onError?: (error: unknown) => void
}

/** @deprecated Use `UseRegisterWebMCPToolsOptions`. Removed in 1.0.0. */
export type UseWebMCPToolsOptions<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
> = UseRegisterWebMCPToolsOptions<TTools, TContext>

type UseRegisterWebMCPToolsArguments<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext,
> =
  RegisterWebMCPToolsOptions<TTools, TContext> extends { context: unknown }
    ? [options: UseRegisterWebMCPToolsOptions<TTools, TContext>]
    : [options?: UseRegisterWebMCPToolsOptions<TTools, TContext>]

/**
 * Registers client tools with WebMCP for the lifetime of a React component.
 *
 * The hook replaces the registration when `tools` or `options` changes.
 * Unsupported browsers and server rendering do not register tools.
 *
 * @param tools - The executable client tools to expose through WebMCP.
 * @param options - Runtime context, per-tool options, and an error callback.
 *
 * @example
 * ```tsx
 * useRegisterWebMCPTools([searchProducts], {
 *   toolOptions: { searchProducts: { title: 'Search products' } },
 * })
 * ```
 */
export function useRegisterWebMCPTools<
  const TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
>(
  tools: TTools,
  ...[options]: UseRegisterWebMCPToolsArguments<TTools, TContext>
) {
  useEffect(() => {
    const controller = new AbortController()
    const { onError, ...registrationOptions } = options ?? {}

    registerWebMCPTools(tools, {
      ...registrationOptions,
      signal: controller.signal,
    }).catch((error) => {
      if (!controller.signal.aborted) onError?.(error)
    })

    return () => controller.abort()
  }, [tools, options])
}

/**
 * @deprecated Use `useRegisterWebMCPTools`. Removed in 1.0.0.
 * @alias
 */
export const useWebMCPTools = useRegisterWebMCPTools

/** Options for {@link usePageWebMCPTools}. */
export type UsePageWebMCPToolsOptions = Omit<
  SubscribeWebMCPToolsOptions,
  'signal'
>

/**
 * Returns the WebMCP tools on the page as client tools for `useChat`.
 *
 * The list starts empty and updates when the page registers or removes a
 * tool. The hook reads the latest `filter` and `onError` on each update.
 * Unsupported browsers and server rendering return an empty array.
 *
 * @param options - A filter that skips tools, and an error callback.
 *
 * @example
 * ```tsx
 * const pageTools = usePageWebMCPTools({
 *   filter: (tool) => tool.origin === location.origin,
 * })
 * const chat = useChat({ connection, tools: pageTools })
 * ```
 */
export function usePageWebMCPTools(
  options?: UsePageWebMCPToolsOptions,
): Array<AnyClientTool> {
  const [tools, setTools] = useState<Array<AnyClientTool>>([])
  const optionsRef = useRef(options)
  optionsRef.current = options

  useEffect(() => {
    const controller = new AbortController()
    subscribeWebMCPTools(setTools, {
      signal: controller.signal,
      filter: (tool) => optionsRef.current?.filter?.(tool) ?? true,
      onError: (error) => optionsRef.current?.onError?.(error),
    })
    return () => controller.abort()
  }, [])

  return tools
}

// packages/ai-solid/src/use-web-mcp-tools.ts
import { createSignal, onCleanup } from 'solid-js'
import { registerWebMCPTools, subscribeWebMCPTools } from '@tanstack/ai-client'
import type { Accessor } from 'solid-js'
import type {
  AnyClientTool,
  InferredClientContext,
  RegisterWebMCPToolsOptions,
  SubscribeWebMCPToolsOptions,
} from '@tanstack/ai-client'

/** Options for {@link useRegisterWebMCPTools}. */
export type UseRegisterWebMCPToolsOptions<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
> = Omit<RegisterWebMCPToolsOptions<TTools, TContext>, 'signal'> & {
  /** Receives an asynchronous registration error. */
  onError?: (error: unknown) => void
}

/** @deprecated Use `UseRegisterWebMCPToolsOptions`. Removed in 1.0.0. */
export type UseWebMCPToolsOptions<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
> = UseRegisterWebMCPToolsOptions<TTools, TContext>

type UseRegisterWebMCPToolsArguments<
  TTools extends ReadonlyArray<AnyClientTool>,
  TContext,
> =
  {} extends UseRegisterWebMCPToolsOptions<TTools, TContext>
    ? [options?: UseRegisterWebMCPToolsOptions<TTools, TContext>]
    : [options: UseRegisterWebMCPToolsOptions<TTools, TContext>]

/**
 * Registers executable client tools with WebMCP for the current Solid owner.
 *
 * The owner cleanup removes every tool registered by this call.
 *
 * @param tools - The executable client tools to expose through WebMCP.
 * @param options - Runtime context, per-tool options, and error handling.
 *
 * @example
 * ```ts
 * useRegisterWebMCPTools([searchProducts])
 * ```
 */
export function useRegisterWebMCPTools<
  const TTools extends ReadonlyArray<AnyClientTool>,
  TContext = InferredClientContext<TTools>,
>(
  tools: TTools,
  ...[options]: UseRegisterWebMCPToolsArguments<TTools, TContext>
) {
  const controller = new AbortController()

  void registerWebMCPTools(tools, {
    ...options,
    signal: controller.signal,
  }).catch((error) => {
    if (!controller.signal.aborted) {
      options?.onError?.(error)
    }
  })

  onCleanup(() => controller.abort())
}

/**
 * @deprecated Use `useRegisterWebMCPTools`. Removed in 1.0.0.
 * @alias
 */
export const useWebMCPTools = useRegisterWebMCPTools

/** Options for {@link usePageWebMCPTools}. */
export type UsePageWebMCPToolsOptions = Omit<
  SubscribeWebMCPToolsOptions,
  'signal'
>

/**
 * Returns the WebMCP tools on the page as client tools for `useChat`.
 *
 * The accessor starts empty and updates when the page registers or removes a
 * tool. The owner cleanup stops the updates. Unsupported browsers and server
 * rendering keep an empty array.
 *
 * @param options - A filter that skips tools, and an error callback.
 *
 * @example
 * ```tsx
 * const pageTools = usePageWebMCPTools({
 *   filter: (tool) => tool.origin === location.origin,
 * })
 * const chat = useChat({
 *   connection,
 *   get tools() {
 *     return pageTools()
 *   },
 * })
 * ```
 */
export function usePageWebMCPTools(
  options?: UsePageWebMCPToolsOptions,
): Accessor<Array<AnyClientTool>> {
  const [tools, setTools] = createSignal<Array<AnyClientTool>>([])
  const controller = new AbortController()

  subscribeWebMCPTools((nextTools) => setTools(nextTools), {
    signal: controller.signal,
    filter: (tool) => options?.filter?.(tool) ?? true,
    onError: (error) => options?.onError?.(error),
  })

  onCleanup(() => controller.abort())
  return tools
}
