// examples/sandbox-cloudflare-agent/src/routes/index.tsx
import { useEffect, useRef, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Send, Server, Square } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import rehypeHighlight from 'rehype-highlight'
import rehypeRaw from 'rehype-raw'
import rehypeSanitize from 'rehype-sanitize'
import remarkGfm from 'remark-gfm'
import { fetchServerSentEvents, useChat } from '@tanstack/ai-react'
import type { UIMessage } from '@tanstack/ai-react'

export const Route = createFileRoute('/')({
  component: SandboxAgentPage,
})

const PROMPT_SUGGESTIONS = [
  'Create a hello.ts that prints "hi" and run it with node.',
  'What files are in the workspace? List them with their sizes.',
  'Write a small Express server and start it, then show me the preview URL.',
]

/** One tool-call invocation from the in-sandbox coding agent (bash, edit, …). */
function ToolCall({
  name,
  args,
  output,
}: {
  name: string
  args: string
  output?: unknown
}) {
  let parsedArgs: unknown = args
  try {
    parsedArgs = JSON.parse(args)
  } catch {
    // leave as the raw string
  }
  const running = output === undefined
  return (
    <div className="mt-3 rounded-lg border border-indigo-500/30 bg-indigo-900/10 overflow-hidden">
      <div className="flex items-center gap-2 px-3 py-2 bg-indigo-900/20 text-indigo-300 text-sm">
        {running ? (
          <div className="w-4 h-4 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
        ) : (
          <div className="w-4 h-4 rounded-full bg-indigo-500/50" />
        )}
        <span className="font-mono font-medium">{name}</span>
      </div>
      <pre className="px-3 py-2 text-xs text-gray-300 overflow-x-auto max-h-40 overflow-y-auto">
        {typeof parsedArgs === 'string'
          ? parsedArgs
          : JSON.stringify(parsedArgs, null, 2)}
      </pre>
      {output !== undefined && (
        <pre className="px-3 pb-3 text-xs text-gray-400 border-t border-indigo-500/20 overflow-x-auto max-h-40 overflow-y-auto">
          {typeof output === 'string' ? output : JSON.stringify(output, null, 2)}
        </pre>
      )}
    </div>
  )
}

function Messages({ messages }: { messages: Array<UIMessage> }) {
  const containerRef = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (containerRef.current) {
      containerRef.current.scrollTop = containerRef.current.scrollHeight
    }
  }, [messages])

  if (!messages.length) {
    return (
      <div className="flex-1 flex items-center justify-center text-gray-500">
        <p>Ask the sandbox coding agent to build or run something…</p>
      </div>
    )
  }

  return (
    <div
      ref={containerRef}
      className="flex-1 overflow-y-auto px-4 py-4"
      style={{ scrollbarWidth: 'thin' }}
    >
      {messages.map((message) => {
        const results = new Map<string, string>()
        for (const part of message.parts) {
          if (part.type === 'tool-result') {
            results.set(
              part.toolCallId,
              typeof part.content === 'string'
                ? part.content
                : JSON.stringify(part.content),
            )
          }
        }
        return (
          <div
            key={message.id}
            className={`p-4 rounded-lg mb-2 ${
              message.role === 'assistant'
                ? 'bg-linear-to-r from-indigo-500/5 to-violet-600/5'
                : 'bg-transparent'
            }`}
          >
            <div className="flex items-start gap-4">
              <div
                className={`w-8 h-8 rounded-lg flex items-center justify-center text-sm font-medium text-white shrink-0 ${
                  message.role === 'assistant'
                    ? 'bg-linear-to-r from-indigo-500 to-violet-600'
                    : 'bg-gray-700'
                }`}
              >
                {message.role === 'assistant' ? 'AI' : 'U'}
              </div>
              <div className="flex-1 min-w-0">
                {message.parts.map((part, index) => {
                  if (part.type === 'text' && part.content) {
                    return (
                      <div key={`text-${index}`} className="markdown-content">
                        <ReactMarkdown
                          remarkPlugins={[remarkGfm]}
                          rehypePlugins={[
                            rehypeRaw,
                            rehypeSanitize,
                            rehypeHighlight,
                          ]}
                        >
                          {part.content}
                        </ReactMarkdown>
                      </div>
                    )
                  }
                  if (part.type === 'tool-call') {
                    const resultContent = results.get(part.id)
                    return (
                      <ToolCall
                        key={part.id}
                        name={part.name}
                        args={part.arguments}
                        output={part.output ?? resultContent}
                      />
                    )
                  }
                  return null
                })}
              </div>
            </div>
          </div>
        )
      })}
    </div>
  )
}

function SandboxAgentPage() {
  // A stable thread id per page load: the agent reuses one sandbox per thread,
  // so every follow-up message lands in the same workspace.
  const [threadId] = useState(() => crypto.randomUUID())
  const [input, setInput] = useState('')

  const { messages, sendMessage, isLoading, stop } = useChat({
    connection: fetchServerSentEvents('/api/run'),
    body: { threadId },
  })

  return (
    <div className="flex flex-col h-screen bg-gray-900">
      <header className="flex items-center justify-between border-b border-indigo-500/10 bg-gray-900/80 px-4 py-3 backdrop-blur-sm">
        <div className="flex items-center gap-2 text-white">
          <Server className="w-5 h-5 text-indigo-400" />
          <span className="font-semibold">Cloudflare Sandbox Agent</span>
          <span className="text-xs text-gray-500">
            Claude Code · Worker → Durable Object → Container
          </span>
        </div>
        <div className="flex items-center gap-2 text-sm text-indigo-300">
          <span className="font-mono">thread {threadId.slice(0, 8)}</span>
        </div>
      </header>

      <div className="flex-1 flex flex-col min-w-0">
        <div className="flex-1 flex flex-col max-w-4xl mx-auto w-full overflow-hidden">
          <Messages messages={messages} />
        </div>

        <div className="border-t border-indigo-500/10 bg-gray-900/80 backdrop-blur-sm">
          <div className="max-w-4xl mx-auto px-4 py-3 space-y-3">
            {isLoading && (
              <div className="flex items-center justify-center">
                <button
                  onClick={stop}
                  className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                >
                  <Square className="w-4 h-4 fill-current" />
                  Stop
                </button>
              </div>
            )}
            <div className="relative">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask the sandbox agent to write or run code…"
                className="w-full rounded-lg border border-indigo-500/20 bg-gray-800/50 pl-4 pr-12 py-3 text-sm text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 resize-none overflow-hidden shadow-lg"
                rows={1}
                style={{ minHeight: '44px', maxHeight: '200px' }}
                disabled={isLoading}
                onInput={(e) => {
                  const target = e.target as HTMLTextAreaElement
                  target.style.height = 'auto'
                  target.style.height = Math.min(target.scrollHeight, 200) + 'px'
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey && input.trim()) {
                    e.preventDefault()
                    sendMessage(input)
                    setInput('')
                  }
                }}
              />
              <button
                onClick={() => {
                  if (input.trim()) {
                    sendMessage(input)
                    setInput('')
                  }
                }}
                disabled={!input.trim() || isLoading}
                className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-indigo-400 hover:text-indigo-300 disabled:text-gray-500 transition-colors focus:outline-none"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>

            <div className="flex flex-wrap gap-2">
              {PROMPT_SUGGESTIONS.map((suggestion) => (
                <button
                  key={suggestion}
                  onClick={() => {
                    if (!isLoading) sendMessage(suggestion)
                  }}
                  disabled={isLoading}
                  className="px-3 py-1.5 text-xs bg-gray-800 hover:bg-gray-700 border border-indigo-500/20 hover:border-indigo-500/40 text-gray-300 hover:text-white rounded-full transition-all disabled:opacity-50"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// examples/ts-solid-chat/src/routes/index.tsx
import { createFileRoute } from "@tanstack/solid-router";
import { Send, Square } from "lucide-solid";
import { SolidMarkdown } from "solid-markdown";
import rehypeRaw from "rehype-raw";
import rehypeSanitize from "rehype-sanitize";
import rehypeHighlight from "rehype-highlight";
import remarkGfm from "remark-gfm";
import {
  useChat,
  fetchServerSentEvents,
  type UIMessage,
} from "@tanstack/ai-solid";

import GuitarRecommendation from "@/components/example-GuitarRecommendation";
import { createSignal, JSXElement } from "solid-js";

function ChatInputArea({ children }: { children: JSXElement }) {
  return (
    <div class="border-t border-orange-500/10 bg-gray-900/80 backdrop-blur-sm">
      <div class="w-full px-4 py-3">{children}</div>
    </div>
  );
}

function Messages(props: {
  messages: Array<UIMessage>;
  addToolApprovalResponse: (response: {
    id: string;
    approved: boolean;
  }) => Promise<void>;
}) {
  if (!props.messages.length) {
    return null;
  }

  return (
    <div class="flex-1 overflow-y-auto px-4 py-4">
      {props.messages.map(({ id, role, parts }) => {
        return (
          <div
            class={`p-4 rounded-lg mb-2 ${
              role === "assistant"
                ? "bg-linear-to-r from-orange-500/5 to-red-600/5"
                : "bg-transparent"
            }`}
          >
            <div class="flex items-start gap-4">
              {role === "assistant" ? (
                <div class="w-8 h-8 rounded-lg bg-linear-to-r from-orange-500 to-red-600 flex items-center justify-center text-sm font-medium text-white flex-shrink-0">
                  AI
                </div>
              ) : (
                <div class="w-8 h-8 rounded-lg bg-gray-700 flex items-center justify-center text-sm font-medium text-white flex-shrink-0">
                  U
                </div>
              )}
              <div class="flex-1 min-w-0">
                {/* Render parts in order */}
                {parts.map((part, index) => {
                  if (part.type === "text" && part.content) {
                    return (
                      <div class="text-white prose dark:prose-invert max-w-none">
                        <SolidMarkdown
                          rehypePlugins={[
                            rehypeRaw,
                            rehypeSanitize,
                            rehypeHighlight,
                            remarkGfm,
                          ]}
                        >
                          {part.content}
                        </SolidMarkdown>
                      </div>
                    );
                  }

                  // Approval UI
                  if (
                    part.type === "tool-call" &&
                    part.state === "approval-requested" &&
                    part.approval
                  ) {
                    return (
                      <div class="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-lg mt-2">
                        <p class="text-white font-medium mb-2">
                          🔒 Approval Required: {part.name}
                        </p>
                        <div class="text-gray-300 text-sm mb-3">
                          <pre class="bg-gray-800 p-2 rounded text-xs overflow-x-auto">
                            {JSON.stringify(
                              JSON.parse(part.arguments),
                              null,
                              2
                            )}
                          </pre>
                        </div>
                        <div class="flex gap-2">
                          <button
                            onClick={() =>
                              props.addToolApprovalResponse({
                                id: part.approval!.id,
                                approved: true,
                              })
                            }
                            class="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium transition-colors"
                          >
                            ✓ Approve
                          </button>
                          <button
                            onClick={() =>
                              props.addToolApprovalResponse({
                                id: part.approval!.id,
                                approved: false,
                              })
                            }
                            class="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-sm font-medium transition-colors"
                          >
                            ✗ Deny
                          </button>
                        </div>
                      </div>
                    );
                  }

                  // Guitar recommendation card
                  if (
                    part.type === "tool-call" &&
                    part.name === "recommendGuitar" &&
                    part.output
                  ) {
                    try {
                      return (
                        <div class="mt-2">
                          <GuitarRecommendation id={part.output.id} />
                        </div>
                      );
                    } catch {
                      return null;
                    }
                  }

                  return null;
                })}
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function DebugPanel(props: {
  messages: Array<UIMessage>;
  chunks: any[];
  onClearChunks: () => void;
}) {
  const [activeTab, setActiveTab] = createSignal<"messages" | "chunks">(
    "messages"
  );

  const exportToTypeScript = () => {
    const tsCode = `const rawChunks = ${JSON.stringify(
      props.chunks,
      null,
      2
    )};`;
    navigator.clipboard.writeText(tsCode);
    alert("TypeScript code copied to clipboard!");
  };

  return (
    <div class="flex flex-col h-full">
      <div class="p-4 border-b border-orange-500/20">
        <h2 class="text-white font-semibold text-lg">Debug Panel</h2>
        <p class="text-gray-400 text-sm mt-1">
          View messages and raw stream chunks
        </p>

        {/* Tabs */}
        <div class="flex gap-2 mt-4">
          <button
            onClick={() => setActiveTab("messages")}
            class={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              activeTab() === "messages"
                ? "bg-orange-500 text-white"
                : "bg-gray-800 text-gray-400 hover:text-white"
            }`}
          >
            Messages
          </button>
          <button
            onClick={() => setActiveTab("chunks")}
            class={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              activeTab() === "chunks"
                ? "bg-orange-500 text-white"
                : "bg-gray-800 text-gray-400 hover:text-white"
            }`}
          >
            Raw Chunks ({props.chunks.length})
          </button>
        </div>
      </div>

      <div class="flex-1 overflow-y-auto p-4">
        {activeTab() === "messages" && (
          <div>
            <pre class="text-xs text-gray-300 font-mono bg-gray-800 p-4 rounded-lg overflow-x-auto">
              {JSON.stringify(props.messages, null, 2)}
            </pre>
          </div>
        )}

        {activeTab() === "chunks" && (
          <div class="space-y-4">
            <div class="flex gap-2">
              <button
                onClick={exportToTypeScript}
                disabled={props.chunks.length === 0}
                class="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 text-white rounded-lg text-sm font-medium transition-colors"
              >
                📋 Export to TypeScript
              </button>
              <button
                onClick={props.onClearChunks}
                disabled={props.chunks.length === 0}
                class="px-4 py-2 bg-red-600 hover:bg-red-700 disabled:bg-gray-600 text-white rounded-lg text-sm font-medium transition-colors"
              >
                🗑️ Clear Chunks
              </button>
            </div>

            {/* Chunks Table */}
            <div class="bg-gray-800 rounded-lg overflow-hidden">
              <table class="w-full text-xs text-left">
                <thead class="bg-gray-900 text-gray-400 uppercase">
                  <tr>
                    <th class="px-4 py-3 w-32">Type</th>
                    <th class="px-4 py-3 w-24">Role</th>
                    <th class="px-4 py-3 w-24">Tool Type</th>
                    <th class="px-4 py-3 w-32">Tool Name</th>
                    <th class="px-4 py-3">Detail</th>
                  </tr>
                </thead>
                <tbody class="text-gray-300">
                  {props.chunks.map((chunk, idx) => {
                    const role = chunk.role || "-";
                    const toolType = chunk.toolCall?.type || "-";
                    const toolName = chunk.toolCall?.function?.name || "-";

                    let detail = "-";
                    if (chunk.type === "content" && chunk.content) {
                      detail = chunk.content;
                    } else if (
                      chunk.type === "tool_call" &&
                      chunk.toolCall?.function?.arguments
                    ) {
                      detail = chunk.toolCall.function.arguments;
                    } else if (chunk.type === "tool_result" && chunk.content) {
                      detail = chunk.content;
                    } else if (chunk.type === "done") {
                      detail = `Finish: ${chunk.finishReason || "unknown"}`;
                    }

                    // Truncate at 200 chars
                    if (detail.length > 200) {
                      detail = detail.substring(0, 200) + "...";
                    }

                    return (
                      <tr class="border-b border-gray-700 hover:bg-gray-750">
                        <td class="px-4 py-3 font-medium">{chunk.type}</td>
                        <td class="px-4 py-3">{role}</td>
                        <td class="px-4 py-3">{toolType}</td>
                        <td class="px-4 py-3">{toolName}</td>
                        <td class="px-4 py-3 font-mono text-xs break-all">
                          {detail}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ChatPage() {
  const [chunks, setChunks] = createSignal<any[]>([]);

  const { messages, sendMessage, isLoading, addToolApprovalResponse, stop } =
    useChat({
      connection: fetchServerSentEvents("/api/tanchat"),
      onChunk: (chunk: any) => {
        setChunks((prev) => [...prev, chunk]);
      },
      onToolCall: async ({ toolName, input }) => {
        // Handle client-side tool execution
        switch (toolName) {
          case "getPersonalGuitarPreference":
            // Pure client tool - executes immediately
            return { preference: "acoustic" };

          case "recommendGuitar":
            // Client tool for UI display
            return { id: input.id };

          case "addToWishList":
            // Hybrid: client execution AFTER approval
            // Only runs after user approves
            const wishList = JSON.parse(
              localStorage.getItem("wishList") || "[]"
            );
            wishList.push(input.guitarId);
            localStorage.setItem("wishList", JSON.stringify(wishList));
            return {
              success: true,
              guitarId: input.guitarId,
              totalItems: wishList.length,
            };

          default:
            throw new Error(`Unknown client tool: ${toolName}`);
        }
      },
    });
  const [input, setInput] = createSignal("");

  const clearChunks = () => setChunks([]);

  return (
    <div class="flex h-[calc(100vh-72px)]  bg-gray-900">
      {/* Left side - Chat (1/4 width) */}
      <div class="w-1/4 flex flex-col border-r border-orange-500/20">
        <div class="p-4 border-b border-orange-500/20">
          <h1 class="text-2xl font-bold bg-linear-to-r from-orange-500 to-red-600 text-transparent bg-clip-text">
            TanStack Chat
          </h1>
          <p class="text-gray-400 text-sm mt-1">
            Parts-based UIMessages with tool states
          </p>
        </div>

        <Messages
          messages={messages()}
          addToolApprovalResponse={addToolApprovalResponse}
        />

        <ChatInputArea>
          <div class="space-y-3">
            {isLoading() && (
              <div class="flex items-center justify-center">
                <button
                  onClick={stop}
                  class="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                >
                  <Square class="w-4 h-4 fill-current" />
                  Stop
                </button>
              </div>
            )}
            <div class="relative">
              <textarea
                value={input()}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Type something clever (or don't, we won't judge)..."
                class="w-full rounded-lg border border-orange-500/20 bg-gray-800/50 pl-4 pr-12 py-3 text-sm text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-500/50 focus:border-transparent resize-none overflow-hidden shadow-lg"
                rows={1}
                style={{ "min-height": "44px", "max-height": "200px" }}
                disabled={isLoading()}
                onInput={(e) => {
                  const target = e.target as HTMLTextAreaElement;
                  target.style.height = "auto";
                  target.style.height =
                    Math.min(target.scrollHeight, 200) + "px";
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey && input().trim()) {
                    e.preventDefault();
                    sendMessage(input());
                    setInput("");
                  }
                }}
              />
              <button
                onClick={() => {
                  if (input().trim()) {
                    sendMessage(input());
                    setInput("");
                  }
                }}
                disabled={!input().trim() || isLoading()}
                class="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-orange-500 hover:text-orange-400 disabled:text-gray-500 transition-colors focus:outline-none"
              >
                <Send class="w-4 h-4" />
              </button>
            </div>
          </div>
        </ChatInputArea>
      </div>

      {/* Right side - Debug Panel (3/4 width) */}
      <div class="w-3/4 bg-gray-950 flex flex-col">
        <DebugPanel
          messages={messages()}
          chunks={chunks()}
          onClearChunks={clearChunks}
        />
      </div>
    </div>
  );
}

export const Route = createFileRoute("/")({
  component: ChatPage,
});
